version: "3.8"

services:
  aj-report:
    container_name: aj-report
    build:
      context: ../..
    restart: always
    ports:
      - 9095:9095
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./build/aj-report-logs:/opt/aj-report/logs
    depends_on:
      - aj-report-mysql

  aj-report-mysql:
    container_name: aj-report-mysql
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: "Asia/Shanghai"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    volumes:
      - ./build/aj-report-mysql:/var/lib/mysql
